In [1]:
import yfinance as yf
import pandas as pd
import logging
import datetime

In [2]:
!pip install lxml

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lxml in /home/spark/.local/lib/python3.10/site-packages (6.0.2)

In [3]:
# Extract Dividend Data from Yahoo Finance API
def extract_dividends_data(symbol):
    """
    Extracts dividend history for a given stock symbol using Yahoo Finance API.
    Parameters:
        symbol (str): Stock ticker symbol (e.g., 'AAPL', 'NVDA')
    Returns:
        pd.DataFrame: DataFrame containing dividend data with metadata
    """

    try:
        ticker = yf.Ticker(symbol)
        dividends = ticker.dividends

        if dividends.empty:
            logging.warning(f"No dividend data found for {symbol}.")
            return pd.DataFrame(columns=["Date", "Dividends", "Symbol", "Ingested_Time"])

        dividends_df = dividends.reset_index()

        print(f"The '{symbol}' dividends data extraction success!")
        logging.info(f"[{symbol}] Dividend data extracted successfully.")
        logging.info(f"Rows: {len(dividends_df)}, Columns: {len(dividends_df.columns)}")
        return dividends_df

    except Exception as e:
        print(f"The ERROR is: {e}")

In [4]:
extract_dividends_data("TSM")

The 'TSM' dividends data extraction success!

                        Date  Dividends
0  2004-06-14 00:00:00-04:00   0.082804
1  2005-06-13 00:00:00-04:00   0.308168
2  2006-06-20 00:00:00-04:00   0.376119
3  2007-06-08 00:00:00-04:00   0.444776
4  2008-07-16 00:00:00-04:00   0.495522
5  2009-07-15 00:00:00-04:00   0.453000
6  2010-07-06 00:00:00-04:00   0.469000
7  2011-06-29 00:00:00-04:00   0.519000
8  2012-07-05 00:00:00-04:00   0.502000
9  2013-07-03 00:00:00-04:00   0.502000
10 2014-07-14 00:00:00-04:00   0.502000
11 2015-06-29 00:00:00-04:00   0.728000
12 2016-06-27 00:00:00-04:00   0.929000
13 2017-06-26 00:00:00-04:00   1.159000
14 2018-06-25 00:00:00-04:00   1.345000
15 2019-06-24 00:00:00-04:00   1.276000
16 2019-09-19 00:00:00-04:00   0.322000
17 2019-12-19 00:00:00-05:00   0.410000
18 2020-03-19 00:00:00-04:00   0.417000
19 2020-06-18 00:00:00-04:00   0.420000
20 2020-09-17 00:00:00-04:00   0.427000
21 2020-12-17 00:00:00-05:00   0.442000
22 2021-03-17 00:00:00-04:00   0.448000
23 2021-06-17 00:00:00-04:00   0.451000
24 2021-09-16 00:00:00-04:00   0.497000
25 2021-12-16 00:00:00-05:00   0.496000
26 2022-03-16 00:00:00-04:00   0.490000
27 2022-06-16 00:00:00-04:00   0.467000
28 2022-09-15 00:00:00-04:00   0.448000
29 2022-12-15 00:00:00-05:00   0.451000
30 2023-03-16 00:00:00-04:00   0.449000
31 2023-06-15 00:00:00-04:00   0.448000
32 2023-09-14 00:00:00-04:00   0.471000
33 2023-12-14 00:00:00-05:00   0.479000
34 2024-03-18 00:00:00-04:00   0.554000
35 2024-06-13 00:00:00-04:00   0.544000
36 2024-09-12 00:00:00-04:00   0.626000
37 2024-12-12 00:00:00-05:00   0.616000
38 2025-03-18 00:00:00-04:00   0.684000
39 2025-06-12 00:00:00-04:00   0.780000
40 2025-09-16 00:00:00-04:00   0.822000
41 2025-12-11 00:00:00-05:00   0.835000

In [5]:
def extract_sp500():
    # S&P 500 index ticker on Yahoo Finance
    ticker = "^GSPC"
    try:
        sp500 = yf.Ticker(ticker)

        # Historical daily prices
        df = sp500.history(period="max")  # You can use '1y', '5y', 'max', etc.
        return df
    except Exception as e:
        print(f"The ERROR is: {e}")

df = extract_sp500()
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1927-12-30 00:00:00-05:00,17.660000,17.660000,17.660000,17.660000,0,0.0,0.0
1928-01-03 00:00:00-05:00,17.760000,17.760000,17.760000,17.760000,0,0.0,0.0
1928-01-04 00:00:00-05:00,17.719999,17.719999,17.719999,17.719999,0,0.0,0.0
1928-01-05 00:00:00-05:00,17.549999,17.549999,17.549999,17.549999,0,0.0,0.0
1928-01-06 00:00:00-05:00,17.660000,17.660000,17.660000,17.660000,0,0.0,0.0
...,...,...,...,...,...,...,...
2026-02-24 00:00:00-05:00,6837.370117,6899.169922,6815.430176,6890.069824,5266090000,0.0,0.0
2026-02-25 00:00:00-05:00,6915.149902,6952.509766,6915.149902,6946.129883,5328060000,0.0,0.0
2026-02-26 00:00:00-05:00,6944.740234,6947.250000,6859.729980,6908.859863,5889550000,0.0,0.0
2026-02-27 00:00:00-05:00,6856.540039,6882.959961,6831.740234,6878.879883,6665660000,0.0,0.0
2026-03-02 00:00:00-05:00,6824.359863,6901.009766,6796.850098,6881.620117,6079080000,0.0,0.0

In [58]:
import requests
import pandas as pd
from io import StringIO

In [59]:
def get_sp500_list():
    # Get the list of S&P 500 companies from a reliable source
    url = "https://www.slickcharts.com/sp500"
    
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    }
    
    response = requests.get(url, headers=headers)
    response.raise_for_status()
    
    try:
        df = pd.read_html(StringIO(response.text))[0]
        df['Symbol'] = df['Symbol'].str.replace('.', '-', regex=False)
        
        sp500_list = df['Symbol'].tolist()
        print("S&P 500 company list extracted successfully.")
        print(f"Total companies in S&P 500: {len(sp500_list)}")
        return sp500_list
    except Exception as e:
        print(f"The ERROR is: {e}")

In [ ]:
# /tmp/ipykernel_207/3130008455.py:13: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
#   df = pd.read_html(response.text)[0]

In [60]:
sp500_list = get_sp500_list()

S&P 500 company list extracted successfully.
Total companies in S&P 500: 503

In [61]:
sp500_list

['NVDA',
 'AAPL',
 'MSFT',
 'AMZN',
 'GOOGL',
 'GOOG',
 'META',
 'TSLA',
 'AVGO',
 'BRK-B',
 'WMT',
 'LLY',
 'JPM',
 'XOM',
 'V',
 'JNJ',
 'MA',
 'MU',
 'COST',
 'ORCL',
 'ABBV',
 'NFLX',
 'PG',
 'CVX',
 'HD',
 'GE',
 'BAC',
 'CAT',
 'PLTR',
 'KO',
 'AMD',
 'CSCO',
 'MRK',
 'AMAT',
 'LRCX',
 'PM',
 'RTX',
 'UNH',
 'MS',
 'GS',
 'WFC',
 'MCD',
 'TMUS',
 'GEV',
 'LIN',
 'PEP',
 'INTC',
 'IBM',
 'AXP',
 'VZ',
 'AMGN',
 'KLAC',
 'ABT',
 'T',
 'C',
 'NEE',
 'TMO',
 'TXN',
 'GILD',
 'DIS',
 'CRM',
 'BA',
 'TJX',
 'ISRG',
 'ADI',
 'DE',
 'SCHW',
 'APH',
 'BLK',
 'ANET',
 'UNP',
 'HON',
 'UBER',
 'LMT',
 'PFE',
 'QCOM',
 'SYK',
 'WELL',
 'ETN',
 'APP',
 'DHR',
 'COP',
 'LOW',
 'NEM',
 'GLW',
 'CB',
 'PLD',
 'SPGI',
 'BKNG',
 'PH',
 'BMY',
 'ACN',
 'MDT',
 'PGR',
 'VRTX',
 'PANW',
 'COF',
 'MCK',
 'HCA',
 'CEG',
 'CME',
 'INTU',
 'MO',
 'NOW',
 'BSX',
 'CMCSA',
 'SBUX',
 'NOC',
 'ADBE',
 'SO',
 'HWM',
 'CVS',
 'TT',
 'DUK',
 'DELL',
 'GD',
 'FCX',
 'WM',
 'UPS',
 'CRWD',
 'EQIX',
 'ICE',
 'WMB',
 'WDC',
 'SNDK',
 'FDX',
 'BX',
 'NKE',
 'MRSH',
 'AMT',
 'JCI',
 'SHW',
 'MAR',
 'PNC',
 'ADP',
 'ECL',
 'EMR',
 'PWR',
 'MMM',
 'USB',
 'ITW',
 'REGN',
 'STX',
 'CDNS',
 'MCO',
 'BK',
 'RCL',
 'SNPS',
 'KKR',
 'CTAS',
 'MSI',
 'CSX',
 'CMI',
 'ORLY',
 'ABNB',
 'MNST',
 'CRH',
 'CL',
 'MDLZ',
 'SLB',
 'DASH',
 'CI',
 'KMI',
 'TDG',
 'COR',
 'AON',
 'AEP',
 'NSC',
 'RSG',
 'HOOD',
 'LHX',
 'WBD',
 'GM',
 'HLT',
 'EOG',
 'TRV',
 'SPG',
 'VLO',
 'PCAR',
 'ROST',
 'ELV',
 'PSX',
 'AZO',
 'BKR',
 'TFC',
 'SRE',
 'TEL',
 'O',
 'MPC',
 'APO',
 'APD',
 'DLR',
 'AJG',
 'FTNT',
 'AFL',
 'NXPI',
 'VST',
 'MPWR',
 'ALL',
 'AME',
 'GWW',
 'PSA',
 'ZTS',
 'OKE',
 'CTVA',
 'CAH',
 'D',
 'KEYS',
 'OXY',
 'F',
 'CARR',
 'FAST',
 'ADSK',
 'URI',
 'TRGP',
 'TGT',
 'TER',
 'FANG',
 'IDXX',
 'EW',
 'FIX',
 'EA',
 'EXC',
 'BDX',
 'NDAQ',
 'CIEN',
 'XEL',
 'GRMN',
 'COIN',
 'ETR',
 'MET',
 'CMG',
 'HSY',
 'ROK',
 'CVNA',
 'AXON',
 'YUM',
 'WAB',
 'FITB',
 'DHI',
 'KR',
 'AIG',
 'ODFL',
 'AMP',
 'SYY',
 'CBRE',
 'PEG',
 'MSCI',
 'PYPL',
 'PCG',
 'DAL',
 'NUE',
 'VTR',
 'KDP',
 'VMC',
 'ED',
 'CCL',
 'MCHP',
 'MLM',
 'EBAY',
 'TTWO',
 'HIG',
 'DDOG',
 'XYZ',
 'CCI',
 'EQT',
 'WEC',
 'LVS',
 'NRG',
 'LYV',
 'RMD',
 'CPRT',
 'IR',
 'TPL',
 'GEHC',
 'ROP',
 'KMB',
 'OTIS',
 'ACGL',
 'EL',
 'KVUE',
 'STT',
 'WDAY',
 'PRU',
 'HBAN',
 'PAYX',
 'DG',
 'ADM',
 'A',
 'FICO',
 'UAL',
 'FISV',
 'EME',
 'MTB',
 'IRM',
 'VICI',
 'EXR',
 'IBKR',
 'TDY',
 'TPR',
 'XYL',
 'AEE',
 'CBOE',
 'ATO',
 'DTE',
 'DOV',
 'RJF',
 'CTSH',
 'WAT',
 'HAL',
 'ULTA',
 'VRSK',
 'IQV',
 'CHTR',
 'FE',
 'STLD',
 'HPE',
 'ROL',
 'PPL',
 'KHC',
 'WTW',
 'EIX',
 'DXCM',
 'CNP',
 'ES',
 'DVN',
 'TSCO',
 'WRB',
 'BIIB',
 'JBL',
 'HUBB',
 'LEN',
 'STZ',
 'NTRS',
 'MTD',
 'PPG',
 'OMC',
 'CINF',
 'AWK',
 'ON',
 'EXPE',
 'EXE',
 'Q',
 'CFG',
 'FIS',
 'PHM',
 'AVB',
 'EFX',
 'ARES',
 'BRO',
 'CHD',
 'SW',
 'STE',
 'DRI',
 'RF',
 'VLTO',
 'GIS',
 'WSM',
 'CMS',
 'CTRA',
 'SYF',
 'DLTR',
 'EQR',
 'LUV',
 'LH',
 'BG',
 'CPAY',
 'DGX',
 'L',
 'KEY',
 'LDOS',
 'TSN',
 'IP',
 'HUM',
 'NI',
 'AMCR',
 'CHRW',
 'DOW',
 'JBHT',
 'CNC',
 'GPN',
 'BR',
 'FSLR',
 'RL',
 'SBAC',
 'ALB',
 'VRSN',
 'PKG',
 'PFG',
 'NVR',
 'TROW',
 'IFF',
 'LULU',
 'MRNA',
 'DD',
 'SNA',
 'INCY',
 'NTAP',
 'ZBH',
 'LII',
 'EXPD',
 'EVRG',
 'CSGP',
 'SMCI',
 'PTC',
 'MKC',
 'LYB',
 'LNT',
 'FTV',
 'WST',
 'VTRS',
 'HII',
 'BALL',
 'TKO',
 'WY',
 'TXT',
 'PODD',
 'HPQ',
 'HOLX',
 'ESS',
 'COO',
 'J',
 'GPC',
 'TRMB',
 'NDSN',
 'CF',
 'DECK',
 'CDW',
 'PNR',
 'INVH',
 'KIM',
 'IEX',
 'FFIV',
 'MAA',
 'APTV',
 'CLX',
 'TYL',
 'AVY',
 'PSKY',
 'REG',
 'MAS',
 'AKAM',
 'BEN',
 'ALLE',
 'ERIE',
 'HAS',
 'EG',
 'HRL',
 'ALGN',
 'HST',
 'GEN',
 'GNRC',
 'DPZ',
 'BF-B',
 'SWK',
 'BBY',
 'UHS',
 'SOLV',
 'UDR',
 'DOC',
 'SJM',
 'PNW',
 'GDDY',
 'JKHY',
 'TTD',
 'AIZ',
 'FOX',
 'GL',
 'IVZ',
 'FOXA',
 'CPT',
 'APA',
 'IT',
 'ZBRA',
 'BLDR',
 'AOS',
 'WYNN',
 'RVTY',
 'DVA',
 'BAX',
 'AES',
 'NCLH',
 'HSIC',
 'FRT',
 'CAG',
 'MGM',
 'TAP',
 'ARE',
 'TECH',
 'BXP',
 'SWKS',
 'NWSA',
 'CRL',
 'MOS',
 'POOL',
 'FDS',
 'MOH',
 'CPB',
 'EPAM',
 'MTCH',
 'PAYC',
 'LW',
 'NWS']

In [34]:
try:
    index = sp500_list.index('BRK-A')
    print(index)
except ValueError:
    print("Not Present")

Not Present

In [41]:
def extract_sp500_profile():
    # S&P 500 index ticker on Yahoo Finance
    try:
        # Get S&P 500 company list
        sp500_list = get_sp500_list()

        # Initialize an empty list to store data
        data_list = []

        for symbol in sp500_list:
            ticker = yf.Ticker(symbol)
            info = ticker.info  # Full metadata

            data_list.append({
                "Exchange": info.get("exchange"),
                "Symbol": symbol,
                "Shortname": info.get("shortName"),
                "Longname": info.get("longName"),
                "Sector": info.get("sector"),
                "Industry": info.get("industry"),
                "Current_Price": info.get("currentPrice"),
                "Current_Price": info.get("currentPrice"),
                "Market_Cap": info.get("marketCap"),
                "Net_Income_To_Common": info.get("netIncomeToCommon"),
                "Ebitda": info.get("ebitda"),
                "Revenue_Growth": info.get("revenueGrowth"),
                "Profit_Margins": info.get("profitMargins"),
                "PE_Ratio": info.get("pe"),
                "Beta": info.get("beta"),
                "Float_Shares": info.get("floatShares"),
                "Shares_Outstanding": info.get("sharesOutstanding"),
                "Shares_Short": info.get("sharesShort"),
                "Shares_Short_Prior_Month": info.get("sharesShortPriorMonth"),
                "Shares_Short_Prev_Month_Date": info.get("sharesShortPreviousMonthDate"),
                "Date_Short_Interest": info.get("dateShortInterest"),
                "Shares_Percent_Shares_Out": info.get("sharesPercentSharesOut"),
                "Short_Ratio": info.get("shortRatio"),
                "Short_Percent_Of_Float": info.get("shortPercentOfFloat"),
                "Held_Percent_Insiders": info.get("heldPercentInsiders"),
                "Held_Percent_Institutions": info.get("heldPercentInstitutions"),
                "Book_Value": info.get("bookValue"),
                "Price_To_Book": info.get("priceToBook"),
                "Last_Fiscal_Year_End": info.get("lastFiscalYearEnd"),
                "Next_Fiscal_Year_End": info.get("nextFiscalYearEnd"),
                "Most_Recent_Quarter": info.get("mostRecentQuarter"),
                "Earnings_Quarterly_Growth": info.get("earningsQuarterlyGrowth"),
                "Net_Income_To_Common": info.get("netIncomeToCommon"),
                "Average_Analyst_Rating": info.get("averageAnalystRating"),
                # "Officers_0_name": info.get("companyOfficers")[0].get("name"),
                # "Officers_0_title": info.get("companyOfficers")[0].get("title"),
                # "Officers_0_yearBorn": info.get("companyOfficers")[0].get("yearBorn"),
                # "Officers_0_fiscalYear": info.get("companyOfficers")[0].get("fiscalYear"),
                # "Officers_0_totalPay": info.get("companyOfficers")[0].get("totalPay"),
                # "Officers_1_name": info.get("companyOfficers")[1].get("name"),
                # "Officers_1_title": info.get("companyOfficers")[1].get("title"),
                # "Officers_1_yearBorn": info.get("companyOfficers")[1].get("yearBorn"),
                # "Officers_1_fiscalYear": info.get("companyOfficers")[1].get("fiscalYear"),
                # "Officers_1_totalPay": info.get("companyOfficers")[1].get("totalPay"),
                # "Officers_2_name": info.get("companyOfficers")[2].get("name"),
                # "Officers_2_title": info.get("companyOfficers")[2].get("title"),
                # "Officers_2_yearBorn": info.get("companyOfficers")[2].get("yearBorn"),
                # "Officers_2_fiscalYear": info.get("companyOfficers")[2].get("fiscalYear"),
                # "Officers_2_totalPay": info.get("companyOfficers")[2].get("totalPay"),
            })

            ## Full version with all fields
            # data_list.append({
            #     "Exchange": info.get("exchange"),
            #     "Symbol": symbol,
            #     "Short_Name": info.get("shortName"),
            #     "Long_Name": info.get("longName"),
            #     "Long_Business_Sum":info.get("longBusinessSummary"),
            #     "Sector": info.get("sector"),
            #     "Industry": info.get("industry"),
            #     "Current_Price": info.get("currentPrice"),
            #     "Market_Cap": info.get("marketCap"),
            #     "Ebitda": info.get("ebitda"),
            #     "All_Time_High": info.get("allTimeHigh"),
            #     "All_Time_Low": info.get("allTimeLow"),
            #     "Price_To_Sales_TTM": info.get("priceToSalesTrailing12Months"),
            #     "Fifty_Day_Avg": info.get("fiftyDayAverage"),
            #     "Two_Hundred_Day_Avg": info.get("twoHundredDayAverage"),
            #     "Trailing_Annual_Dividend_Rate": info.get("trailingAnnualDividendRate"),
            #     "Trailing_Annual_Dividend_Yield": info.get("trailingAnnualDividendYield"),
            #     "Currency": info.get("currency"),
            #     "Tradeable": info.get("tradeable"),
            #     "Quote_Type": info.get("quoteType"),
            #     "Enterprise_Value": info.get("enterpriseValue"),
            #     "Profit_Margins": info.get("profitMargins"),
            #     "Float_Shares": info.get("floatShares"),
            #     "Shares_Outstanding": info.get("sharesOutstanding"),
            #     "Shares_Short": info.get("sharesShort"),
            #     "Shares_Short_Prior_Month": info.get("sharesShortPriorMonth"),
            #     "Shares_Short_Prev_Month_Date": info.get("sharesShortPreviousMonthDate"),
            #     "Date_Short_Interest": info.get("dateShortInterest"),
            #     "Shares_Percent_Shares_Out": info.get("sharesPercentSharesOut"),
            #     "Short_Ratio": info.get("shortRatio"),
            #     "Short_Percent_Of_Float": info.get("shortPercentOfFloat"),
            #     "Held_Percent_Insiders": info.get("heldPercentInsiders"),
            #     "Held_Percent_Institutions": info.get("heldPercentInstitutions"),
            #     "Book_Value": info.get("bookValue"),
            #     "Price_To_Book": info.get("priceToBook"),
            #     "Last_Fiscal_Year_End": info.get("lastFiscalYearEnd"),
            #     "Next_Fiscal_Year_End": info.get("nextFiscalYearEnd"),
            #     "Most_Recent_Quarter": info.get("mostRecentQuarter"),
            #     "Earnings_Quarterly_Growth": info.get("earningsQuarterlyGrowth"),
            #     "Net_Income_To_Common": info.get("netIncomeToCommon"),
            #     "Average_Analyst_Rating": info.get("averageAnalystRating"),
            #     "Officers_0_name": info.get("companyOfficers")[0].get("name"),
            #     "Officers_0_title": info.get("companyOfficers")[0].get("title"),
            #     "Officers_0_yearBorn": info.get("companyOfficers")[0].get("yearBorn"),
            #     "Officers_0_fiscalYear": info.get("companyOfficers")[0].get("fiscalYear"),
            #     "Officers_0_totalPay": info.get("companyOfficers")[0].get("totalPay"),
            #     "Officers_1_name": info.get("companyOfficers")[1].get("name"),
            #     "Officers_1_title": info.get("companyOfficers")[1].get("title"),
            #     "Officers_1_yearBorn": info.get("companyOfficers")[1].get("yearBorn"),
            #     "Officers_1_fiscalYear": info.get("companyOfficers")[1].get("fiscalYear"),
            #     "Officers_1_totalPay": info.get("companyOfficers")[1].get("totalPay"),
            #     "Officers_2_name": info.get("companyOfficers")[2].get("name"),
            #     "Officers_2_title": info.get("companyOfficers")[2].get("title"),
            #     "Officers_2_yearBorn": info.get("companyOfficers")[2].get("yearBorn"),
            #     "Officers_2_fiscalYear": info.get("companyOfficers")[2].get("fiscalYear"),
            #     "Officers_2_totalPay": info.get("companyOfficers")[2].get("totalPay"),
            #     "Officers_3_name": info.get("companyOfficers")[3].get("name"),
            #     "Officers_3_title": info.get("companyOfficers")[3].get("title"),
            #     "Officers_3_yearBorn": info.get("companyOfficers")[3].get("yearBorn"),
            #     "Officers_3_fiscalYear": info.get("companyOfficers")[3].get("fiscalYear"),
            #     "Officers_3_totalPay": info.get("companyOfficers")[3].get("totalPay"),
            #     "Officers_4_name": info.get("companyOfficers")[4].get("name"),
            #     "Officers_4_title": info.get("companyOfficers")[4].get("title"),
            #     "Officers_4_yearBorn": info.get("companyOfficers")[4].get("yearBorn"),
            #     "Officers_4_fiscalYear": info.get("companyOfficers")[4].get("fiscalYear"),
            #     "Officers_4_totalPay": info.get("companyOfficers")[4].get("totalPay"),
            #     "Officers_5_name": info.get("companyOfficers")[5].get("name"),
            #     "Officers_5_title": info.get("companyOfficers")[5].get("title"),
            #     "Officers_5_yearBorn": info.get("companyOfficers")[5].get("yearBorn"),
            #     "Officers_5_fiscalYear": info.get("companyOfficers")[5].get("fiscalYear"),
            #     "Officers_5_totalPay": info.get("companyOfficers")[5].get("totalPay"),
            #     "Officers_6_name": info.get("companyOfficers")[6].get("name"),
            #     "Officers_6_title": info.get("companyOfficers")[6].get("title"),
            #     "Officers_6_yearBorn": info.get("companyOfficers")[6].get("yearBorn"),
            #     "Officers_6_fiscalYear": info.get("companyOfficers")[6].get("fiscalYear"),
            #     "Officers_6_totalPay": info.get("companyOfficers")[6].get("totalPay"),
            #     "Officers_7_name": info.get("companyOfficers")[7].get("name"),
            #     "Officers_7_title": info.get("companyOfficers")[7].get("title"),
            #     "Officers_7_yearBorn": info.get("companyOfficers")[7].get("yearBorn"),
            #     "Officers_7_fiscalYear": info.get("companyOfficers")[7].get("fiscalYear"),
            #     "Officers_7_totalPay": info.get("companyOfficers")[7].get("totalPay"),
            #     "Officers_8_name": info.get("companyOfficers")[8].get("name"),
            #     "Officers_8_title": info.get("companyOfficers")[8].get("title"),
            #     "Officers_8_yearBorn": info.get("companyOfficers")[8].get("yearBorn"),
            #     "Officers_8_fiscalYear": info.get("companyOfficers")[8].get("fiscalYear"),
            #     "Officers_8_totalPay": info.get("companyOfficers")[8].get("totalPay"),
            #     "Officers_9_name": info.get("companyOfficers")[9].get("name"),
            #     "Officers_9_title": info.get("companyOfficers")[9].get("title"),
            #     "Officers_9_yearBorn": info.get("companyOfficers")[9].get("yearBorn"),
            #     "Officers_9_fiscalYear": info.get("companyOfficers")[9].get("fiscalYear"),
            #     "Officers_9_totalPay": info.get("companyOfficers")[9].get("totalPay"),
            # })

            sp_profile_df = pd.DataFrame(data_list)
        return sp_profile_df
    except Exception as e:
        print(f"The ERROR is: {e}")


def extract_sp500_price_history():
    # S&P 500 index ticker on Yahoo Finance
    try:
        # Get S&P 500 company list
        sp500_list = get_sp500_list()

        # Initialize an empty list to store data
        data_list = []

        for symbol in sp500_list:
            ticker = yf.Ticker(symbol)
            hist = ticker.history(period='1mo', interval='1d', start=None, end=None)  # Historical price data

            hist.reset_index(inplace=True)
            hist['Symbol'] = symbol  # Add symbol column

            data_list.append(hist)

            sp_price_history_df = pd.concat(data_list, ignore_index=True)
        return sp_price_history_df
    except Exception as e:
        print(f"The ERROR is: {e}")

In [42]:
extract_sp500_profile = extract_sp500_profile()
extract_sp500_profile

/tmp/ipykernel_207/3130008455.py:13: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(response.text)[0]

S&P 500 company list extracted successfully.
Total companies in S&P 500: 503

,Exchange,Symbol,Shortname,Longname,Sector,Industry,Current_Price,Market_Cap,Net_Income_To_Common,Ebitda,...,Short_Percent_Of_Float,Held_Percent_Insiders,Held_Percent_Institutions,Book_Value,Price_To_Book,Last_Fiscal_Year_End,Next_Fiscal_Year_End,Most_Recent_Quarter,Earnings_Quarterly_Growth,Average_Analyst_Rating
0,NMS,NVDA,NVIDIA Corporation,NVIDIA Corporation,Technology,Semiconductors,182.48,4435176587264,1.200670e+11,1.332300e+11,...,0.0109,0.04354,0.69651,6.472,28.195301,1.769299e+09,1.800835e+09,1.769299e+09,0.945,1.3 - Strong Buy
1,NMS,AAPL,Apple Inc.,Apple Inc.,Technology,Consumer Electronics,264.72,3890834833408,1.177770e+11,1.529020e+11,...,0.0091,0.01840,0.65176,5.998,44.134712,1.758931e+09,1.790467e+09,1.766794e+09,0.159,1.9 - Buy
2,NMS,MSFT,Microsoft Corporation,Microsoft Corporation,Technology,Software - Infrastructure,398.55,2962173984768,1.192620e+11,1.752590e+11,...,0.0076,0.00309,0.75859,52.615,7.574836,1.751242e+09,1.782778e+09,1.767139e+09,0.595,1.3 - Strong Buy
3,NMS,AMZN,"Amazon.com, Inc.","Amazon.com, Inc.",Consumer Cyclical,Internet Retail,208.39,2237050126336,7.767000e+10,1.457310e+11,...,0.0090,0.09271,0.67207,38.306,5.440140,1.767139e+09,1.798675e+09,1.767139e+09,0.059,1.3 - Strong Buy
4,NMS,GOOGL,Alphabet Inc.,Alphabet Inc.,Communication Services,Internet Content & Information,306.52,3707972354048,1.321700e+11,1.501750e+11,...,0.0126,0.00809,0.80775,34.353,8.922655,1.767139e+09,1.798675e+09,1.767139e+09,0.298,1.4 - Strong Buy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,NYQ,EPAM,"EPAM Systems, Inc.","EPAM Systems, Inc.",Technology,Information Technology Services,139.16,7687563264,3.776780e+08,7.072300e+08,...,0.0832,0.03887,1.05225,67.753,2.053931,1.767139e+09,1.798675e+09,1.767139e+09,0.059,1.8 - Buy
499,NMS,MTCH,"Match Group, Inc.","Match Group, Inc.",Communication Services,Internet Content & Information,31.29,7529067008,6.134460e+08,1.052699e+09,...,0.0646,0.00716,1.08463,-1.090,-28.706423,1.767139e+09,1.798675e+09,1.767139e+09,0.324,2.4 - Buy
500,NYQ,PAYC,"Paycom Software, Inc.","Paycom Software, Inc.",Technology,Software - Application,128.30,7044455424,4.534000e+08,6.345000e+08,...,0.1016,0.13139,0.98249,32.364,3.964282,1.767139e+09,1.798675e+09,1.767139e+09,0.002,2.4 - Buy
501,NYQ,LW,"Lamb Weston Holdings, Inc.","Lamb Weston Holdings, Inc.",Consumer Defensive,Packaged Foods,46.78,6518908928,3.923000e+08,1.231000e+09,...,0.0572,0.03219,0.94088,12.633,3.703000,1.748131e+09,1.779667e+09,1.763856e+09,NaN,None
502,NMS,NWS,News Corporation,News Corporation,Communication Services,Entertainment,26.41,14619868160,4.390000e+08,1.187000e+09,...,0.1417,0.34350,0.47663,15.767,1.675017,1.751242e+09,1.782778e+09,1.767139e+09,-0.102,1.6 - Buy

In [43]:
ticker = yf.Ticker("NVDA")
info = ticker.info
info

{'address1': '2788 San Tomas Expressway',
 'city': 'Santa Clara',
 'state': 'CA',
 'zip': '95051',
 'country': 'United States',
 'phone': '408-486-2000',
 'website': 'https://www.nvidia.com',
 'industry': 'Semiconductors',
 'industryKey': 'semiconductors',
 'industryDisp': 'Semiconductors',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "NVIDIA Corporation, a computing infrastructure company, provides graphics and compute and networking solutions in the United States, Taiwan, China, Hong Kong, and internationally. It operates through Compute & Networking and Graphics segments. The Compute & Networking segment includes its Data Center accelerated computing and networking platforms and artificial intelligence solutions and software and automotive platforms and autonomous and electric vehicle solutions, including software. The Graphics segment offers GeForce GPUs for gaming and PCs; Quadro/NVIDIA RTX GPUs for enterprise workstation graphics; GeForce NOW cloud gaming service; and NVIDIA vGPU software for graphics- virtual desktops and workstations. It also develops standalone software solutions, including NVIDIA AI Enterprise, NVIDIA Omniverse, NVIDIA DRIVE, and other software products. The company's products are used in gaming, professional visualization, data center, and automotive markets. It sells its products to original equipment manufacturers, original device manufacturers, system integrators and distributors, independent software vendors, cloud service providers, add-in board manufacturers, distributors, automotive manufacturers and tier-1 automotive suppliers, and other ecosystem participants. NVIDIA Corporation was incorporated in 1993 and is headquartered in Santa Clara, California.",
 'fullTimeEmployees': 42000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Jen-Hsun  Huang',
   'age': 62,
   'title': 'Co-Founder, CEO, President & Director',
   'yearBorn': 1963,
   'fiscalYear': 2025,
   'totalPay': 11054945,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Colette M. Kress',
   'age': 58,
   'title': 'Executive VP & CFO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 1512641,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Debora  Shoquist',
   'age': 70,
   'title': 'Executive Vice President of Operations',
   'yearBorn': 1955,
   'fiscalYear': 2025,
   'totalPay': 1379071,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Timothy S. Teter J.D.',
   'age': 58,
   'title': 'Executive VP, General Counsel & Secretary',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 1362989,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ajay K. Puri',
   'age': 70,
   'title': 'Executive Vice President of Worldwide Field Operations',
   'yearBorn': 1955,
   'fiscalYear': 2025,
   'totalPay': 2313851,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris A. Malachowsky',
   'title': 'Co-Founder',
   'fiscalYear': 2025,
   'totalPay': 320000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Donald F. Robertson Jr.',
   'age': 56,
   'title': 'VP & Chief Accounting Officer',
   'yearBorn': 1969,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Prof. William J. Dally Ph.D.',
   'age': 64,
   'title': 'Chief Scientist & Senior VP of Research',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Toshiya  Hari',
   'title': 'Vice President of Investor Relations & Strategic Finance',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Mylene  Mangalindan',
   'title': 'Vice President of Corporate Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 5,
 'boardRisk': 9,
 'compensationRisk': 4,
 'shareHolderRightsRisk': 8,
 'overallRisk': 8,
 'governanceEpochDate': 1772323200,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://phx.corporate-ir.net/phoenix.zhtml?c=116466&p=irol-IRHome',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 177.19,
 'open': 174.8,
 'dayLow': 174.64,
 'dayHigh': 183.46,
 'regularMarketPreviousClose': 177.19,
 'regularMarketOpen': 174.8,
 'regularMarketDayLow': 174.64,
 'regularMarketDayHigh': 183.46,
 'dividendRate': 0.04,
 'dividendYield': 0.02,
 'exDividendDate': 1773187200,
 'payoutRatio': 0.0082,
 'fiveYearAvgDividendYield': 0.05,
 'beta': 2.375,
 'trailingPE': 37.16497,
 'forwardPE': 17.086046,
 'volume': 206465519,
 'regularMarketVolume': 206465519,
 'averageVolume': 174661255,
 'averageVolume10days': 206256740,
 'averageDailyVolume10Day': 206256740,
 'bid': 182.3,
 'ask': 182.62,
 'bidSize': 1,
 'askSize': 1,
 'marketCap': 4435176587264,
 'nonDilutedMarketCap': 4434264000000,
 'fiftyTwoWeekLow': 86.62,
 'fiftyTwoWeekHigh': 212.19,
 'allTimeHigh': 212.19,
 'allTimeLow': 0.033333,
 'priceToSalesTrailing12Months': 20.53912,
 'fiftyDayAverage': 185.621,
 'twoHundredDayAverage': 174.9574,
 'trailingAnnualDividendRate': 0.04,
 'trailingAnnualDividendYield': 0.00022574636,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 4383120031744,
 'profitMargins': 0.55603004,
 'floatShares': 23330673000,
 'sharesOutstanding': 24300000000,
 'sharesShort': 254311707,
 'sharesShortPriorMonth': 261838673,
 'sharesShortPreviousMonthDate': 1768435200,
 'dateShortInterest': 1770940800,
 'sharesPercentSharesOut': 0.0105,
 'heldPercentInsiders': 0.04354,
 'heldPercentInstitutions': 0.69651,
 'shortRatio': 1.45,
 'shortPercentOfFloat': 0.0109,
 'impliedSharesOutstanding': 24305000000,
 'bookValue': 6.472,
 'priceToBook': 28.195301,
 'lastFiscalYearEnd': 1769299200,
 'nextFiscalYearEnd': 1800835200,
 'mostRecentQuarter': 1769299200,
 'earningsQuarterlyGrowth': 0.945,
 'netIncomeToCommon': 120066998272,
 'trailingEps': 4.91,
 'forwardEps': 10.68006,
 'lastSplitFactor': '10:1',
 'lastSplitDate': 1717977600,
 'enterpriseToRevenue': 20.298,
 'enterpriseToEbitda': 32.899,
 '52WeekChange': 0.52763164,
 'SandP52WeekChange': 0.19049871,
 'lastDividendValue': 0.01,
 'lastDividendDate': 1764806400,
 'quoteType': 'EQUITY',
 'currentPrice': 182.48,
 'targetHighPrice': 380.0,
 'targetLowPrice': 140.0,
 'targetMeanPrice': 264.24878,
 'targetMedianPrice': 263.915,
 'recommendationMean': 1.28333,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 58,
 'totalCash': 62556000256,
 'totalCashPerShare': 2.574,
 'ebitda': 133230002176,
 'totalDebt': 11411999744,
 'quickRatio': 3.141,
 'currentRatio': 3.905,
 'totalRevenue': 215938007040,
 'debtToEquity': 7.255,
 'revenuePerShare': 8.865,
 'returnOnAssets': 0.51188,
 'returnOnEquity': 1.01485,
 'grossProfits': 153462996992,
 'freeCashflow': 58128998400,
 'operatingCashflow': 102717997056,
 'earningsGrowth': 0.956,
 'revenueGrowth': 0.732,
 'grossMargins': 0.71068,
 'ebitdaMargins': 0.61698,
 'operatingMargins': 0.65024,
 'financialCurrency': 'USD',
 'symbol': 'NVDA',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'regularMarketChangePercent': 2.98549,
 'regularMarketPrice': 182.48,
 'marketState': 'PREPRE',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 917015400000,
 'postMarketChangePercent': -0.5757333,
 'postMarketPrice': 181.4294,
 'postMarketChange': -1.0505981,
 'regularMarketChange': 5.28999,
 'regularMarketDayRange': '174.64 - 183.46',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 174661255,
 'fiftyTwoWeekLowChange': 95.85999,
 'fiftyTwoWeekLowChangePercent': 1.1066728,
 'fiftyTwoWeekRange': '86.62 - 212.19',
 'fiftyTwoWeekHighChange': -29.710007,
 'fiftyTwoWeekHighChangePercent': -0.14001605,
 'fiftyTwoWeekChangePercent': 52.763165,
 'dividendDate': 1766707200,
 'earningsTimestamp': 1779310800,
 'earningsTimestampStart': 1779310800,
 'earningsTimestampEnd': 1779310800,
 'earningsCallTimestampStart': 1772056800,
 'earningsCallTimestampEnd': 1772056800,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 4.91,
 'epsForward': 10.68006,
 'epsCurrentYear': 8.24798,
 'priceEpsCurrentYear': 22.124205,
 'fiftyDayAverageChange': -3.1410065,
 'fiftyDayAverageChangePercent': -0.016921612,
 'twoHundredDayAverageChange': 7.5225983,
 'twoHundredDayAverageChangePercent': 0.04299674,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'prevName': 'Usual Stablecoin',
 'nameChangeDate': '2026-03-02',
 'averageAnalystRating': '1.3 - Strong Buy',
 'corporateActions': [{'header': 'Dividend',
   'message': 'NVDA announced a cash dividend of 0.01$ with an ex-date of Mar. 11, 2026',
   'meta': {'eventType': 'DIVIDEND',
    'dateEpochMs': 1773205200000,
    'amount': '0.01'}}],
 'postMarketTime': 1772499599,
 'regularMarketTime': 1772485201,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_32307',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EST',
 'gmtOffSetMilliseconds': -18000000,
 'market': 'us_market',
 'esgPopulated': False,
 'shortName': 'NVIDIA Corporation',
 'longName': 'NVIDIA Corporation',
 'cryptoTradeable': False,
 'displayName': 'NVIDIA',
 'trailingPegRatio': 1.1073}

In [62]:
def extract_sp500_profile():
    sp500_list = get_sp500_list()
    data_list = []

    for symbol in sp500_list:
        try:
            ticker = yf.Ticker(symbol)
            info = ticker.info

            info["symbol"] = symbol  # ensure symbol column exists
            data_list.append(info)

        except Exception as e:
            print(f"Error for {symbol}: {e}")

    return pd.DataFrame(data_list)

df = extract_sp500_profile()
df

S&P 500 company list extracted successfully.
Total companies in S&P 500: 503

,address1,city,state,zip,country,phone,website,industry,industryKey,industryDisp,...,isEarningsDateEstimate,epsTrailingTwelveMonths,epsForward,epsCurrentYear,displayName,trailingPegRatio,ipoExpectedDate,address2,fax,industrySymbol
0,2788 San Tomas Expressway,Santa Clara,CA,95051,United States,408-486-2000,https://www.nvidia.com,Semiconductors,semiconductors,Semiconductors,...,False,4.91,10.68006,8.24798,NVIDIA,1.1073,NaN,NaN,NaN,NaN
1,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,consumer-electronics,Consumer Electronics,...,False,7.89,9.30443,8.50190,Apple,2.3708,NaN,NaN,NaN,NaN
2,One Microsoft Way,Redmond,WA,98052-6399,United States,425 882 8080,https://www.microsoft.com,Software - Infrastructure,software-infrastructure,Software - Infrastructure,...,False,15.98,18.84224,16.72920,Microsoft,1.3002,NaN,NaN,NaN,NaN
3,410 Terry Avenue North,Seattle,WA,98109-5210,United States,206 266 1000,https://www.amazon.com,Internet Retail,internet-retail,Internet Retail,...,True,7.17,9.33570,7.71683,Amazon.com,1.9050,NaN,NaN,NaN,NaN
4,1600 Amphitheatre Parkway,Mountain View,CA,94043,United States,650-253-0000,https://abc.xyz,Internet Content & Information,internet-content-information,Internet Content & Information,...,False,10.82,13.41329,11.56931,NaN,2.3079,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,41 University Drive,Newtown,PA,18940,United States,267 759 9000,https://www.epam.com,Information Technology Services,information-technology-services,Information Technology Services,...,True,6.72,13.94380,12.73354,EPAM Systems,0.8374,NaN,Suite 202,267 759 8989,NaN
499,8750 North Central Expressway,Dallas,TX,75231,United States,214 576 9352,https://www.mtch.com,Internet Content & Information,internet-content-information,Internet Content & Information,...,False,2.38,4.03037,3.62886,Match,0.3277,NaN,Suite 1400,NaN,NaN
500,7501 West Memorial Road,Oklahoma City,OK,73142,United States,405 722 6900,https://www.paycom.com,Software - Application,software-application,Software - Application,...,True,8.08,11.30368,10.23033,Paycom Software,1.1504,NaN,NaN,NaN,NaN
501,599 South Rivershore Lane,Eagle,ID,83616,United States,208 938 1047,https://www.lambweston.com,Packaged Foods,packaged-foods,Packaged Foods,...,False,2.76,3.01238,2.74613,Lamb Weston,0.6781,NaN,NaN,NaN,NaN
502,1211 Avenue of the Americas,New York,NY,10036,United States,212 416 3400,https://newscorp.com,Entertainment,entertainment,Entertainment,...,True,0.77,1.24231,1.06103,News,NaN,NaN,NaN,NaN,NaN

In [68]:
companyOfficers = df['website']
companyOfficers

0          https://www.nvidia.com
1           https://www.apple.com
2       https://www.microsoft.com
3          https://www.amazon.com
4                 https://abc.xyz
                  ...
498          https://www.epam.com
499          https://www.mtch.com
500        https://www.paycom.com
501    https://www.lambweston.com
502          https://newscorp.com
Name: website, Length: 503, dtype: object

In [67]:
cols = df.columns.tolist()
cols

['address1',
 'city',
 'state',
 'zip',
 'country',
 'phone',
 'website',
 'industry',
 'industryKey',
 'industryDisp',
 'sector',
 'sectorKey',
 'sectorDisp',
 'longBusinessSummary',
 'fullTimeEmployees',
 'companyOfficers',
 'auditRisk',
 'boardRisk',
 'compensationRisk',
 'shareHolderRightsRisk',
 'overallRisk',
 'governanceEpochDate',
 'compensationAsOfEpochDate',
 'irWebsite',
 'executiveTeam',
 'maxAge',
 'priceHint',
 'previousClose',
 'open',
 'dayLow',
 'dayHigh',
 'regularMarketPreviousClose',
 'regularMarketOpen',
 'regularMarketDayLow',
 'regularMarketDayHigh',
 'dividendRate',
 'dividendYield',
 'exDividendDate',
 'payoutRatio',
 'fiveYearAvgDividendYield',
 'beta',
 'trailingPE',
 'forwardPE',
 'volume',
 'regularMarketVolume',
 'averageVolume',
 'averageVolume10days',
 'averageDailyVolume10Day',
 'bid',
 'ask',
 'bidSize',
 'askSize',
 'marketCap',
 'nonDilutedMarketCap',
 'fiftyTwoWeekLow',
 'fiftyTwoWeekHigh',
 'allTimeHigh',
 'allTimeLow',
 'priceToSalesTrailing12Months',
 'fiftyDayAverage',
 'twoHundredDayAverage',
 'trailingAnnualDividendRate',
 'trailingAnnualDividendYield',
 'currency',
 'tradeable',
 'enterpriseValue',
 'profitMargins',
 'floatShares',
 'sharesOutstanding',
 'sharesShort',
 'sharesShortPriorMonth',
 'sharesShortPreviousMonthDate',
 'dateShortInterest',
 'sharesPercentSharesOut',
 'heldPercentInsiders',
 'heldPercentInstitutions',
 'shortRatio',
 'shortPercentOfFloat',
 'impliedSharesOutstanding',
 'bookValue',
 'priceToBook',
 'lastFiscalYearEnd',
 'nextFiscalYearEnd',
 'mostRecentQuarter',
 'earningsQuarterlyGrowth',
 'netIncomeToCommon',
 'trailingEps',
 'forwardEps',
 'lastSplitFactor',
 'lastSplitDate',
 'enterpriseToRevenue',
 'enterpriseToEbitda',
 '52WeekChange',
 'SandP52WeekChange',
 'lastDividendValue',
 'lastDividendDate',
 'quoteType',
 'currentPrice',
 'targetHighPrice',
 'targetLowPrice',
 'targetMeanPrice',
 'targetMedianPrice',
 'recommendationMean',
 'recommendationKey',
 'numberOfAnalystOpinions',
 'totalCash',
 'totalCashPerShare',
 'ebitda',
 'totalDebt',
 'quickRatio',
 'currentRatio',
 'totalRevenue',
 'debtToEquity',
 'revenuePerShare',
 'returnOnAssets',
 'returnOnEquity',
 'grossProfits',
 'freeCashflow',
 'operatingCashflow',
 'earningsGrowth',
 'revenueGrowth',
 'grossMargins',
 'ebitdaMargins',
 'operatingMargins',
 'financialCurrency',
 'symbol',
 'language',
 'region',
 'typeDisp',
 'quoteSourceName',
 'triggerable',
 'customPriceAlertConfidence',
 'exchange',
 'messageBoardId',
 'exchangeTimezoneName',
 'exchangeTimezoneShortName',
 'gmtOffSetMilliseconds',
 'market',
 'esgPopulated',
 'corporateActions',
 'postMarketTime',
 'regularMarketTime',
 'shortName',
 'longName',
 'marketState',
 'priceEpsCurrentYear',
 'fiftyDayAverageChange',
 'fiftyDayAverageChangePercent',
 'twoHundredDayAverageChange',
 'twoHundredDayAverageChangePercent',
 'sourceInterval',
 'exchangeDataDelayedBy',
 'prevName',
 'nameChangeDate',
 'averageAnalystRating',
 'cryptoTradeable',
 'regularMarketChangePercent',
 'regularMarketPrice',
 'hasPrePostMarketData',
 'firstTradeDateMilliseconds',
 'postMarketChangePercent',
 'postMarketPrice',
 'postMarketChange',
 'regularMarketChange',
 'regularMarketDayRange',
 'fullExchangeName',
 'averageDailyVolume3Month',
 'fiftyTwoWeekLowChange',
 'fiftyTwoWeekLowChangePercent',
 'fiftyTwoWeekRange',
 'fiftyTwoWeekHighChange',
 'fiftyTwoWeekHighChangePercent',
 'fiftyTwoWeekChangePercent',
 'dividendDate',
 'earningsTimestamp',
 'earningsTimestampStart',
 'earningsTimestampEnd',
 'earningsCallTimestampStart',
 'earningsCallTimestampEnd',
 'isEarningsDateEstimate',
 'epsTrailingTwelveMonths',
 'epsForward',
 'epsCurrentYear',
 'displayName',
 'trailingPegRatio',
 'ipoExpectedDate',
 'address2',
 'fax',
 'industrySymbol']