In [8]:
import logging
from pyspark import SparkConf
from pyspark import SparkContext
from pyspark.sql import SparkSession
from pyspark.sql import functions as sf
from pyspark.sql.functions import month, days
from pyspark.sql.types import StructType, StructField, LongType, DoubleType, StringType, TimestampNTZType

In [9]:
app_name = "Testing ETL Finance profiles"

spark = (
        SparkSession.builder
        .master("spark://spark-master:7077")
        .appName(app_name)
        .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")
        .config("spark.sql.catalog.lakehouse_prod","org.apache.iceberg.spark.SparkCatalog")
        .config("spark.sql.catalog.lakehouse_prod.type", "hive")
        .config("spark.sql.catalog.lakehouse_prod.uri","thrift://hive-metastore:9083")
        .config("spark.sql.catalog.lakehouse_prod.warehouse","s3a://lakehouse-prod-bucket/warehouse/")
        .config("spark.sql.catalog.lakehouse_prod.io-impl","org.apache.iceberg.aws.s3.S3FileIO")
        .config("spark.hadoop.fs.s3a.endpoint", "http://minio:9000")
        .config("spark.hadoop.fs.s3a.path.style.access", "true")
        .config("spark.hadoop.fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")
        .config("spark.hadoop.fs.s3a.connection.ssl.enabled", "false")
        .config("spark.sql.adaptive.enabled", "true")
        .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
        .enableHiveSupport()
        .getOrCreate()
)

spark.sparkContext.setLogLevel("ERROR")
print("NOTE: SparkSession created successfully!")

NOTE: SparkSession created successfully!

In [3]:
spark

In [5]:
file_path = "./data/sp500_profiles.csv"
df = spark.read.csv(file_path, header=True, inferSchema=True)

In [9]:
df.toPandas()

,address1,city,state,zip,country,phone,website,industry,industryKey,industryDisp,...,regularMarketDayRange,marketState,regularMarketChangePercent,regularMarketPrice,displayName,trailingPegRatio,ipoExpectedDate,address2,fax,industrySymbol
0,2788 San Tomas Expressway,Santa Clara,CA,95051,United States,408-486-2000,https://www.nvidia.com,Semiconductors,semiconductors,Semiconductors,...,None,None,None,None,None,NaN,None,None,None,None
1,{'age': 58.0,'exercisedValue': 0,'fiscalYear': 2025.0,'maxAge': 1,'name': 'Ms. Colette M. Kress','title': 'Executive VP & CFO','totalPay': 1512641.0,'unexercisedValue': 0,'yearBorn': 1967.0},None,...,None,None,None,None,None,NaN,None,None,None,None
2,{'age': 70.0,'exercisedValue': 0,'fiscalYear': 2025.0,'maxAge': 1,'name': 'Ms. Debora Shoquist','title': 'Executive Vice President of Operati...,'totalPay': 1379071.0,'unexercisedValue': 0,'yearBorn': 1955.0},None,...,None,None,None,None,None,NaN,None,None,None,None
3,{'age': 58.0,'exercisedValue': 0,'fiscalYear': 2025.0,'maxAge': 1,'name': 'Mr. Timothy S. Teter J.D.','title': 'Executive VP,General Counsel & Secretary','totalPay': 1362989.0,'unexercisedValue': 0,'yearBorn': 1967.0},...,None,None,None,None,None,NaN,None,None,None,None
4,{'age': 70.0,'exercisedValue': 0,'fiscalYear': 2025.0,'maxAge': 1,'name': 'Mr. Ajay K. Puri','title': 'Executive Vice President of Worldwi...,'totalPay': 2313851.0,'unexercisedValue': 0,'yearBorn': 1955.0},None,...,None,None,None,None,None,NaN,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,{'age': 52.0,'exercisedValue': 0,'fiscalYear': 2025.0,'maxAge': 1,'name': 'Mr. Julian Delany','title': 'Executive VP & Chief Technology Off...,'totalPay': None,'unexercisedValue': 0,'yearBorn': 1973.0},None,...,None,None,None,None,None,NaN,None,None,None,None
4800,{'age': None,'exercisedValue': 0,'fiscalYear': 2025.0,'maxAge': 1,'name': 'Mr. Michael Florin','title': 'Senior VP & Head of Investor Relati...,'totalPay': None,'unexercisedValue': 0,'yearBorn': None},None,...,None,None,None,None,None,NaN,None,None,None,None
4801,{'age': None,'exercisedValue': 0,'fiscalYear': 2025.0,'maxAge': 1,'name': 'Mr. Arthur Bochner','title': 'Executive VP & Chief Communications...,'totalPay': None,'unexercisedValue': 0,'yearBorn': None},None,...,None,None,None,None,None,NaN,None,None,None,None
4802,{'age': None,'exercisedValue': 0,'fiscalYear': 2025.0,'maxAge': 1,'name': 'Ms. Anoushka Healy','title': 'Executive VP & Chief Strategy Officer','totalPay': None,'unexercisedValue': 0,'yearBorn': None},None,...,None,None,None,None,None,NaN,None,None,None,None
4803,{'age': None,'exercisedValue': 0,'fiscalYear': 2025.0,'maxAge': 1,'name': 'Mr. Michael L. Bunder','title': 'Senior VP,Deputy General Counsel & Corporate Secretary','totalPay': None,'unexercisedValue': 0,"'yearBorn': None}]""",...,None,None,None,None,None,NaN,None,None,None,None

In [10]:
df.printSchema()

root
 |-- address1: string (nullable = true)
 |-- city: string (nullable = true)
 |-- state: string (nullable = true)
 |-- zip: string (nullable = true)
 |-- country: string (nullable = true)
 |-- phone: string (nullable = true)
 |-- website: string (nullable = true)
 |-- industry: string (nullable = true)
 |-- industryKey: string (nullable = true)
 |-- industryDisp: string (nullable = true)
 |-- sector: string (nullable = true)
 |-- sectorKey: string (nullable = true)
 |-- sectorDisp: string (nullable = true)
 |-- longBusinessSummary: string (nullable = true)
 |-- fullTimeEmployees: string (nullable = true)
 |-- companyOfficers: string (nullable = true)
 |-- auditRisk: string (nullable = true)
 |-- boardRisk: string (nullable = true)
 |-- compensationRisk: string (nullable = true)
 |-- shareHolderRightsRisk: string (nullable = true)
 |-- overallRisk: string (nullable = true)
 |-- governanceEpochDate: string (nullable = true)
 |-- compensationAsOfEpochDate: string (nullable = true)
 |-- irWebsite: string (nullable = true)
 |-- executiveTeam: string (nullable = true)
 |-- maxAge: string (nullable = true)
 |-- priceHint: string (nullable = true)
 |-- previousClose: string (nullable = true)
 |-- open: string (nullable = true)
 |-- dayLow: string (nullable = true)
 |-- dayHigh: string (nullable = true)
 |-- regularMarketPreviousClose: string (nullable = true)
 |-- regularMarketOpen: double (nullable = true)
 |-- regularMarketDayLow: double (nullable = true)
 |-- regularMarketDayHigh: double (nullable = true)
 |-- dividendRate: double (nullable = true)
 |-- dividendYield: double (nullable = true)
 |-- exDividendDate: double (nullable = true)
 |-- payoutRatio: double (nullable = true)
 |-- fiveYearAvgDividendYield: double (nullable = true)
 |-- beta: double (nullable = true)
 |-- trailingPE: double (nullable = true)
 |-- forwardPE: double (nullable = true)
 |-- volume: double (nullable = true)
 |-- regularMarketVolume: double (nullable = true)
 |-- averageVolume: double (nullable = true)
 |-- averageVolume10days: long (nullable = true)
 |-- averageDailyVolume10Day: double (nullable = true)
 |-- bid: double (nullable = true)
 |-- ask: double (nullable = true)
 |-- bidSize: double (nullable = true)
 |-- askSize: double (nullable = true)
 |-- marketCap: double (nullable = true)
 |-- nonDilutedMarketCap: double (nullable = true)
 |-- fiftyTwoWeekLow: double (nullable = true)
 |-- fiftyTwoWeekHigh: double (nullable = true)
 |-- allTimeHigh: string (nullable = true)
 |-- allTimeLow: string (nullable = true)
 |-- priceToSalesTrailing12Months: string (nullable = true)
 |-- fiftyDayAverage: string (nullable = true)
 |-- twoHundredDayAverage: string (nullable = true)
 |-- trailingAnnualDividendRate: double (nullable = true)
 |-- trailingAnnualDividendYield: double (nullable = true)
 |-- currency: string (nullable = true)
 |-- tradeable: string (nullable = true)
 |-- enterpriseValue: double (nullable = true)
 |-- profitMargins: double (nullable = true)
 |-- floatShares: double (nullable = true)
 |-- sharesOutstanding: double (nullable = true)
 |-- sharesShort: double (nullable = true)
 |-- sharesShortPriorMonth: double (nullable = true)
 |-- sharesShortPreviousMonthDate: double (nullable = true)
 |-- dateShortInterest: double (nullable = true)
 |-- sharesPercentSharesOut: double (nullable = true)
 |-- heldPercentInsiders: double (nullable = true)
 |-- heldPercentInstitutions: double (nullable = true)
 |-- shortRatio: double (nullable = true)
 |-- shortPercentOfFloat: double (nullable = true)
 |-- impliedSharesOutstanding: double (nullable = true)
 |-- bookValue: double (nullable = true)
 |-- priceToBook: double (nullable = true)
 |-- lastFiscalYearEnd: string (nullable = true)
 |-- nextFiscalYearEnd: string (nullable = true)
 |-- mostRecentQuarter: string (nullable = true)
 |-- earningsQuarterlyGrowth: string (nullable = true)
 |-- netIncomeToCommon: double (nullable = true)
 |-- trailingEps: double (nullable = true)
 |-- forwardEps: double (nullable = true)
 |-- lastSplitFactor: string (nullable = true)
 |-- lastSplitDate: string (nullable = true)
 |-- enterpriseToRevenue: string (nullable = true)
 |-- enterpriseToEbitda: string (nullable = true)
 |-- 52WeekChange: string (nullable = true)
 |-- SandP52WeekChange: double (nullable = true)
 |-- lastDividendValue: double (nullable = true)
 |-- lastDividendDate: double (nullable = true)
 |-- quoteType: string (nullable = true)
 |-- currentPrice: string (nullable = true)
 |-- targetHighPrice: string (nullable = true)
 |-- targetLowPrice: string (nullable = true)
 |-- targetMeanPrice: double (nullable = true)
 |-- targetMedianPrice: double (nullable = true)
 |-- recommendationMean: double (nullable = true)
 |-- recommendationKey: string (nullable = true)
 |-- numberOfAnalystOpinions: double (nullable = true)
 |-- totalCash: double (nullable = true)
 |-- totalCashPerShare: double (nullable = true)
 |-- ebitda: double (nullable = true)
 |-- totalDebt: double (nullable = true)
 |-- quickRatio: double (nullable = true)
 |-- currentRatio: double (nullable = true)
 |-- totalRevenue: double (nullable = true)
 |-- debtToEquity: double (nullable = true)
 |-- revenuePerShare: double (nullable = true)
 |-- returnOnAssets: double (nullable = true)
 |-- returnOnEquity: double (nullable = true)
 |-- grossProfits: double (nullable = true)
 |-- freeCashflow: string (nullable = true)
 |-- operatingCashflow: string (nullable = true)
 |-- earningsGrowth: string (nullable = true)
 |-- revenueGrowth: string (nullable = true)
 |-- grossMargins: string (nullable = true)
 |-- ebitdaMargins: string (nullable = true)
 |-- operatingMargins: string (nullable = true)
 |-- financialCurrency: string (nullable = true)
 |-- symbol: string (nullable = true)
 |-- language: string (nullable = true)
 |-- region: string (nullable = true)
 |-- typeDisp: string (nullable = true)
 |-- quoteSourceName: string (nullable = true)
 |-- triggerable: string (nullable = true)
 |-- customPriceAlertConfidence: string (nullable = true)
 |-- cryptoTradeable: string (nullable = true)
 |-- shortName: string (nullable = true)
 |-- longName: string (nullable = true)
 |-- exchange: string (nullable = true)
 |-- messageBoardId: string (nullable = true)
 |-- exchangeTimezoneName: string (nullable = true)
 |-- exchangeTimezoneShortName: string (nullable = true)
 |-- gmtOffSetMilliseconds: string (nullable = true)
 |-- market: string (nullable = true)
 |-- esgPopulated: string (nullable = true)
 |-- fullExchangeName: string (nullable = true)
 |-- averageDailyVolume3Month: double (nullable = true)
 |-- fiftyTwoWeekLowChange: double (nullable = true)
 |-- fiftyTwoWeekLowChangePercent: double (nullable = true)
 |-- fiftyTwoWeekRange: string (nullable = true)
 |-- fiftyTwoWeekHighChange: double (nullable = true)
 |-- fiftyTwoWeekHighChangePercent: double (nullable = true)
 |-- fiftyTwoWeekChangePercent: string (nullable = true)
 |-- dividendDate: string (nullable = true)
 |-- earningsTimestamp: string (nullable = true)
 |-- earningsTimestampStart: string (nullable = true)
 |-- earningsTimestampEnd: double (nullable = true)
 |-- earningsCallTimestampStart: double (nullable = true)
 |-- earningsCallTimestampEnd: double (nullable = true)
 |-- isEarningsDateEstimate: string (nullable = true)
 |-- epsTrailingTwelveMonths: double (nullable = true)
 |-- epsForward: double (nullable = true)
 |-- epsCurrentYear: double (nullable = true)
 |-- priceEpsCurrentYear: string (nullable = true)
 |-- fiftyDayAverageChange: string (nullable = true)
 |-- fiftyDayAverageChangePercent: string (nullable = true)
 |-- twoHundredDayAverageChange: string (nullable = true)
 |-- twoHundredDayAverageChangePercent: string (nullable = true)
 |-- sourceInterval: string (nullable = true)
 |-- exchangeDataDelayedBy: string (nullable = true)
 |-- prevName: string (nullable = true)
 |-- nameChangeDate: string (nullable = true)
 |-- averageAnalystRating: string (nullable = true)
 |-- corporateActions: string (nullable = true)
 |-- regularMarketTime: string (nullable = true)
 |-- hasPrePostMarketData: string (nullable = true)
 |-- firstTradeDateMilliseconds: string (nullable = true)
 |-- regularMarketChange: string (nullable = true)
 |-- regularMarketDayRange: string (nullable = true)
 |-- marketState: string (nullable = true)
 |-- regularMarketChangePercent: string (nullable = true)
 |-- regularMarketPrice: string (nullable = true)
 |-- displayName: string (nullable = true)
 |-- trailingPegRatio: double (nullable = true)
 |-- ipoExpectedDate: date (nullable = true)
 |-- address2: string (nullable = true)
 |-- fax: string (nullable = true)
 |-- industrySymbol: string (nullable = true)

In [11]:
df.groupBy(df.symbol).count().sort("symbol").show()

[Stage 7:>                                                          (0 + 1) / 1]

+--------------------+-----+
|              symbol|count|
+--------------------+-----+
|                NULL| 4301|
|                 CNP|    1|
|                 ETN|    1|
|                FISV|    1|
|               False|  430|
|                HIGH|   56|
|                MPWR|    1|
|Nasdaq Real Time ...|    4|
|                PYPL|    1|
|                 TMO|    1|
|                True|    7|
+--------------------+-----+

In [3]:
# Define the S3 path (using s3a protocol)
s3_bucket_path = "s3a://datalake-landing/profiles/sp500_profiles_20260308.parquet"

# Read CSV data from S3 into a DataFrame
df = spark.read.parquet(s3_bucket_path, header=True, inferSchema=True)

# Show data
df.toPandas()

26/03/10 17:19:40 ERROR TransportClient: Failed to send RPC RPC 8557441231021552839 to /172.22.0.10:51834: io.netty.channel.StacklessClosedChannelException
io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
26/03/10 17:19:40 ERROR TransportClient: Failed to send RPC RPC 8741911515642610483 to /172.22.0.9:54960: io.netty.channel.StacklessClosedChannelException
io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)

,address1,city,state,zip,country,phone,website,industry,industryKey,industryDisp,...,isEarningsDateEstimate,epsTrailingTwelveMonths,epsForward,epsCurrentYear,displayName,trailingPegRatio,ipoExpectedDate,address2,fax,industrySymbol
0,2788 San Tomas Expressway,Santa Clara,CA,95051,United States,408-486-2000,https://www.nvidia.com,Semiconductors,semiconductors,Semiconductors,...,False,4.91,10.74220,8.24943,NVIDIA,1.0750,None,None,None,None
1,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,consumer-electronics,Consumer Electronics,...,True,7.90,9.28890,8.49805,Apple,2.3044,None,None,None,None
2,One Microsoft Way,Redmond,WA,98052-6399,United States,425 882 8080,https://www.microsoft.com,Software - Infrastructure,software-infrastructure,Software - Infrastructure,...,True,15.99,18.84224,16.72920,Microsoft,1.3341,None,None,None,None
3,410 Terry Avenue North,Seattle,WA,98109-5210,United States,206 266 1000,https://www.amazon.com,Internet Retail,internet-retail,Internet Retail,...,True,7.16,9.33864,7.72036,Amazon.com,1.9491,None,None,None,None
4,1600 Amphitheatre Parkway,Mountain View,CA,94043,United States,650-253-0000,https://abc.xyz,Internet Content & Information,internet-content-information,Internet Content & Information,...,True,10.81,13.42320,11.57674,None,2.2467,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,200 Oceangate,Long Beach,CA,90802,United States,(562) 435-3666,https://www.molinahealthcare.com,Healthcare Plans,healthcare-plans,Healthcare Plans,...,False,8.91,10.23591,6.95756,Molina Healthcare,0.5679,None,Suite 100,None,None
499,7501 West Memorial Road,Oklahoma City,OK,73142,United States,405 722 6900,https://www.paycom.com,Software - Application,software-application,Software - Application,...,True,8.07,11.40768,10.31768,Paycom Software,1.2254,None,None,None,None
500,8750 North Central Expressway,Dallas,TX,75231,United States,214 576 9352,https://mtch.com,Internet Content & Information,internet-content-information,Internet Content & Information,...,True,2.38,4.03037,3.62886,Match,0.3194,None,Suite 1400,None,None
501,599 South Rivershore Lane,Eagle,ID,83616,United States,208 938 1047,https://www.lambweston.com,Packaged Foods,packaged-foods,Packaged Foods,...,False,2.76,3.01460,2.74724,Lamb Weston,0.6477,None,None,None,None
502,1211 Avenue of the Americas,New York,NY,10036,United States,212 416 3400,https://newscorp.com,Entertainment,entertainment,Entertainment,...,True,0.77,1.24231,1.06103,News,NaN,None,None,None,None

In [4]:
duplicate_rows = df.count() - df.dropDuplicates().count()
duplicate_rows

0

In [5]:
df.groupBy("industry").count().sort("count", ascending=False).show()

+--------------------+-----+
|            industry|count|
+--------------------+-----+
|Utilities - Regul...|   23|
|Specialty Industr...|   17|
|Software - Applic...|   16|
|Software - Infras...|   15|
|      Semiconductors|   13|
|    Asset Management|   13|
| Aerospace & Defense|   12|
|Diagnostics & Res...|   11|
|     Medical Devices|   10|
|       Entertainment|   10|
|Information Techn...|   10|
|       Oil & Gas E&P|   10|
| Specialty Chemicals|    9|
|Drug Manufacturer...|    9|
|Medical Instrumen...|    9|
|Financial Data & ...|    9|
|    Banks - Regional|    9|
|Insurance - Prope...|    8|
|      Packaged Foods|    8|
|   Computer Hardware|    7|
+--------------------+-----+
only showing top 20 rows

In [9]:
df.select('*').show(5)

+--------------------+-------------+-----+----------+-------------+--------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-----------------+--------------------+---------+---------+----------------+---------------------+-----------+-------------------+-------------------------+--------------------+-------------+------+---------+-------------+------+--------+--------+--------------------------+-----------------+-------------------+--------------------+------------+-------------+--------------+-----------+------------------------+-----+----------+---------+---------+-------------------+-------------+-------------------+-----------------------+------+------+-------+-------+-------------+-------------------+---------------+----------------+-----------+----------+----------------------------+---------------+--------------------+--------------------------+---------------------------+--------+---------+-----------------+-------------+---------------+-----------------+------------+---------------------+----------------------------+-----------------+----------------------+-------------------+-----------------------+----------+-------------------+------------------------+---------+-----------+-----------------+-----------------+-----------------+-----------------------+-----------------+-----------+----------+---------------+-------------+-------------------+------------------+------------+-----------------+-----------------+----------------+---------+------------+---------------+--------------+---------------+-----------------+------------------+-----------------+-----------------------+----------------+-----------------+----------------+----------------+----------+------------+----------------+------------+---------------+--------------+--------------+----------------+----------------+-----------------+--------------+-------------+------------+-------------+----------------+-----------------+------+--------+------+--------+--------------------+-----------+--------------------------+--------+--------------+--------------------+-------------------------+---------------------+---------+------------+----------------+--------------+-----------------+--------------------+--------------------+-----------+-------------------+---------------------+----------------------------+--------------------------+---------------------------------+--------------+---------------------+----------------+--------------+--------------------+---------------+--------------------------+------------------+--------------------+--------------------------+-----------------------+---------------+----------------+-------------------+---------------------+----------------+------------------------+---------------------+----------------------------+-----------------+----------------------+-----------------------------+-------------------------+------------+-----------------+----------------------+--------------------+--------------------------+------------------------+----------------------+-----------------------+----------+--------------+-----------+----------------+---------------+--------+----+--------------+
|            address1|         city|state|       zip|      country|         phone|             website|            industry|         industryKey|        industryDisp|              sector|           sectorKey|          sectorDisp| longBusinessSummary|fullTimeEmployees|     companyOfficers|auditRisk|boardRisk|compensationRisk|shareHolderRightsRisk|overallRisk|governanceEpochDate|compensationAsOfEpochDate|           irWebsite|executiveTeam|maxAge|priceHint|previousClose|  open|  dayLow| dayHigh|regularMarketPreviousClose|regularMarketOpen|regularMarketDayLow|regularMarketDayHigh|dividendRate|dividendYield|exDividendDate|payoutRatio|fiveYearAvgDividendYield| beta|trailingPE|forwardPE|   volume|regularMarketVolume|averageVolume|averageVolume10days|averageDailyVolume10Day|   bid|   ask|bidSize|askSize|    marketCap|nonDilutedMarketCap|fiftyTwoWeekLow|fiftyTwoWeekHigh|allTimeHigh|allTimeLow|priceToSalesTrailing12Months|fiftyDayAverage|twoHundredDayAverage|trailingAnnualDividendRate|trailingAnnualDividendYield|currency|tradeable|  enterpriseValue|profitMargins|    floatShares|sharesOutstanding| sharesShort|sharesShortPriorMonth|sharesShortPreviousMonthDate|dateShortInterest|sharesPercentSharesOut|heldPercentInsiders|heldPercentInstitutions|shortRatio|shortPercentOfFloat|impliedSharesOutstanding|bookValue|priceToBook|lastFiscalYearEnd|nextFiscalYearEnd|mostRecentQuarter|earningsQuarterlyGrowth|netIncomeToCommon|trailingEps|forwardEps|lastSplitFactor|lastSplitDate|enterpriseToRevenue|enterpriseToEbitda|52WeekChange|SandP52WeekChange|lastDividendValue|lastDividendDate|quoteType|currentPrice|targetHighPrice|targetLowPrice|targetMeanPrice|targetMedianPrice|recommendationMean|recommendationKey|numberOfAnalystOpinions|       totalCash|totalCashPerShare|          ebitda|       totalDebt|quickRatio|currentRatio|    totalRevenue|debtToEquity|revenuePerShare|returnOnAssets|returnOnEquity|    grossProfits|    freeCashflow|operatingCashflow|earningsGrowth|revenueGrowth|grossMargins|ebitdaMargins|operatingMargins|financialCurrency|symbol|language|region|typeDisp|     quoteSourceName|triggerable|customPriceAlertConfidence|exchange|messageBoardId|exchangeTimezoneName|exchangeTimezoneShortName|gmtOffSetMilliseconds|   market|esgPopulated|corporateActions|postMarketTime|regularMarketTime|           shortName|            longName|marketState|priceEpsCurrentYear|fiftyDayAverageChange|fiftyDayAverageChangePercent|twoHundredDayAverageChange|twoHundredDayAverageChangePercent|sourceInterval|exchangeDataDelayedBy|        prevName|nameChangeDate|averageAnalystRating|cryptoTradeable|regularMarketChangePercent|regularMarketPrice|hasPrePostMarketData|firstTradeDateMilliseconds|postMarketChangePercent|postMarketPrice|postMarketChange|regularMarketChange|regularMarketDayRange|fullExchangeName|averageDailyVolume3Month|fiftyTwoWeekLowChange|fiftyTwoWeekLowChangePercent|fiftyTwoWeekRange|fiftyTwoWeekHighChange|fiftyTwoWeekHighChangePercent|fiftyTwoWeekChangePercent|dividendDate|earningsTimestamp|earningsTimestampStart|earningsTimestampEnd|earningsCallTimestampStart|earningsCallTimestampEnd|isEarningsDateEstimate|epsTrailingTwelveMonths|epsForward|epsCurrentYear|displayName|trailingPegRatio|ipoExpectedDate|address2| fax|industrySymbol|
+--------------------+-------------+-----+----------+-------------+--------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-----------------+--------------------+---------+---------+----------------+---------------------+-----------+-------------------+-------------------------+--------------------+-------------+------+---------+-------------+------+--------+--------+--------------------------+-----------------+-------------------+--------------------+------------+-------------+--------------+-----------+------------------------+-----+----------+---------+---------+-------------------+-------------+-------------------+-----------------------+------+------+-------+-------+-------------+-------------------+---------------+----------------+-----------+----------+----------------------------+---------------+--------------------+--------------------------+---------------------------+--------+---------+-----------------+-------------+---------------+-----------------+------------+---------------------+----------------------------+-----------------+----------------------+-------------------+-----------------------+----------+-------------------+------------------------+---------+-----------+-----------------+-----------------+-----------------+-----------------------+-----------------+-----------+----------+---------------+-------------+-------------------+------------------+------------+-----------------+-----------------+----------------+---------+------------+---------------+--------------+---------------+-----------------+------------------+-----------------+-----------------------+----------------+-----------------+----------------+----------------+----------+------------+----------------+------------+---------------+--------------+--------------+----------------+----------------+-----------------+--------------+-------------+------------+-------------+----------------+-----------------+------+--------+------+--------+--------------------+-----------+--------------------------+--------+--------------+--------------------+-------------------------+---------------------+---------+------------+----------------+--------------+-----------------+--------------------+--------------------+-----------+-------------------+---------------------+----------------------------+--------------------------+---------------------------------+--------------+---------------------+----------------+--------------+--------------------+---------------+--------------------------+------------------+--------------------+--------------------------+-----------------------+---------------+----------------+-------------------+---------------------+----------------+------------------------+---------------------+----------------------------+-----------------+----------------------+-----------------------------+-------------------------+------------+-----------------+----------------------+--------------------+--------------------------+------------------------+----------------------+-----------------------+----------+--------------+-----------+----------------+---------------+--------+----+--------------+
|2788 San Tomas Ex...|  Santa Clara|   CA|     95051|United States|  408-486-2000|https://www.nvidi...|      Semiconductors|      semiconductors|      Semiconductors|          Technology|          technology|          Technology|NVIDIA Corporatio...|          42000.0|[{62.0, 0, 2025.0...|      5.0|      9.0|             4.0|                  8.0|        8.0|        1.7723232E9|              1.7671392E9|http://phx.corpor...|           []| 86400|        2|       183.34|179.84|176.8201|182.7561|                    183.34|           179.84|           176.8201|            182.7561|        0.04|         0.02|   1.7731872E9|     0.0082|                    0.05|2.375|  36.21589|16.553408|187239412|          187239412|    176132166|          222196790|              222196790|176.85|178.47|     50|    100|4321915437056|      4321026000000|          86.62|          212.19|     212.19|  0.033333|                   20.014612|        186.006|            176.1357|                      0.04|               2.1817388E-4|     USD|    false|4.269881950208E12|   0.55603004|   2.3330673E10|      24300000000|2.54311707E8|         2.61838673E8|                 1.7684352E9|      1.7709408E9|                0.0105|             0.0421|                0.69701|      1.45|             0.0109|               2.4305E10|    6.472|  27.475279|      1.7692992E9|      1.8008352E9|      1.7692992E9|                  0.945| 1.20066998272E11|       4.91|   10.7422|           10:1|  1.7179776E9|             19.774|            32.049|   0.6621798|       0.20045388|             0.01|     1.7648064E9|   EQUITY|      177.82|          380.0|         140.0|      265.18298|            265.0|           1.28814|       strong_buy|                   57.0| 6.2556000256E10|            2.574|1.33230002176E11| 1.1411999744E10|     3.141|       3.905| 2.1593800704E11|       7.255|          8.865|       0.51188|       1.01485|1.53462996992E11|   5.81289984E10| 1.02717997056E11|         0.956|        0.732|     0.71068|      0.61698|         0.65024|              USD|  NVDA|   en-US|    US|  Equity|Nasdaq Real Time ...|       true|                      HIGH|     NMS|   finmb_32307|    America/New_York|                      EDT|            -14400000|us_market|       false|              []|    1772845198|       1772830802|  NVIDIA Corporation|  NVIDIA Corporation|     CLOSED|           21.55543|            -8.185989|                -0.044009276|                 1.6843109|                      0.009562575|            15|                    0|Usual Stablecoin|    2026-03-07|    1.3 - Strong Buy|          false|                  -3.01079|            177.82|                true|              917015400000|             0.11809214|         178.03|      0.20999146|           -5.51999|  176.8201 - 182.7561|        NasdaqGS|               176132166|            91.200005|                   1.0528747|   86.62 - 212.19|            -34.369995|                  -0.16197746|                 66.21798| 1.7667072E9|      1.7793072E9|            1779307200|          1779307200|               1.7720568E9|             1.7720568E9|                 false|                   4.91|   10.7422|       8.24943|     NVIDIA|           1.075|           NULL|    NULL|NULL|          NULL|
|  One Apple Park Way|    Cupertino|   CA|     95014|United States|(408) 996-1010|https://www.apple...|Consumer Electronics|consumer-electronics|Consumer Electronics|          Technology|          technology|          Technology|Apple Inc. design...|         150000.0|[{64.0, 0, 2025.0...|      2.0|      1.0|             7.0|                  1.0|        1.0|        1.7723232E9|              1.7671392E9|http://investor.a...|           []| 86400|        2|       260.29|258.74|  254.37|  258.76|                    260.29|           258.74|             254.37|              258.76|        1.04|          0.4|   1.7705952E9|     0.1304|                    0.52|1.116|  32.58987|27.716951| 40628988|           40628988|     48185950|           43370120|               43370120|256.93|271.51|      2|      1|3784127807488|      3779806304400|         169.21|          288.62|     288.62|  0.049107|                    8.686823|       264.2878|           244.17625|                      1.03|               0.0039571244|     USD|    false|3.803408236544E12|      0.27037|1.4656182062E10|      14681140000|1.33373267E8|         1.13576032E8|                 1.7684352E9|      1.7709408E9|                0.0091|            0.01637|             0.65200996|      2.32|             0.0091|            1.4697926E10|    5.998|  42.924305|      1.7589312E9|      1.7904672E9|      1.7667936E9|                  0.159|   1.177769984E11|        7.9|    9.2889|            4:1|   1.598832E9|              8.731|            24.875|  0.13179183|       0.20045388|             0.26|     1.7705952E9|   EQUITY|      257.46|          350.0|         205.0|      292.14624|            300.0|           1.91667|              buy|                   40.0| 6.6907000832E10|            4.557|1.52901992448E11| 9.0509000704E10|     0.845|       0.974|4.35617005568E11|      102.63|         29.305|       0.24377|     1.5202099|  2.061570048E11|1.06312753152E11| 1.35471996928E11|         0.183|        0.157|     0.47325|   0.35099998|         0.35374|              USD|  AAPL|   en-US|    US|  Equity|Nasdaq Real Time ...|       true|                      HIGH|     NMS|   finmb_24937|    America/New_York|                      EDT|            -14400000|us_market|       false|              []|    1772845199|       1772830802|          Apple Inc.|          Apple Inc.|     CLOSED|          30.296362|             -6.82782|                 -0.02583479|                 13.283737|                      0.054402247|            15|                    0|            NULL|          NULL|           1.9 - Buy|          false|                  -1.08726|            257.46|                true|              345479400000|            -0.31461105|         256.65|     -0.80999756|           -2.83002|      254.37 - 258.76|        NasdaqGS|                48185950|            88.249985|                   0.5215412|  169.21 - 288.62|            -31.160004|                  -0.10796204|                13.179183| 1.7708544E9|      1.7697204E9|            1777579200|          1777579200|                1.769724E9|              1.769724E9|                  true|                    7.9|    9.2889|       8.49805|      Apple|          2.3044|           NULL|    NULL|NULL|          NULL|
|   One Microsoft Way|      Redmond|   WA|98052-6399|United States|  425 882 8080|https://www.micro...|Software - Infras...|software-infrastr...|Software - Infras...|          Technology|          technology|          Technology|Microsoft Corpora...|         228000.0|[{58.0, 0, 2025.0...|      9.0|      8.0|             5.0|                  2.0|        6.0|        1.7723232E9|              1.7671392E9|http://www.micros...|           []| 86400|        2|       410.68| 409.3|408.5101|  413.05|                    410.68|            409.3|           408.5101|              413.05|        3.64|         0.89|   1.7714592E9| 0.21280001|                    0.79|1.108| 25.575985|21.704426| 30792826|           30792826|     33590203|           38609000|               38609000|408.77|409.55|      2|      2|3039545262080|      3036785266920|         344.79|          555.45|     555.45|  0.088542|                    9.950942|       437.7534|           484.55515|                      3.48|                0.008473751|     USD|    false|3.070601199616E12|      0.39044|  7.414861914E9|       7425629076|  5.612454E7|          5.4651789E7|                 1.7684352E9|      1.7709408E9|                0.0076|             7.9E-4|                  0.759|      1.29|             0.0076|           7.432377656E9|   52.615|   7.772688|      1.7512416E9|      1.7827776E9|      1.7671392E9|                  0.595|   1.192620032E11|      15.99|  18.84224|            2:1|  1.0455264E9|             10.053|             17.52|  0.07575762|       0.20045388|             0.91|     1.7714592E9|   EQUITY|      408.96|          730.0|         392.0|      595.99567|            600.0|            1.2807|       strong_buy|                   53.0| 8.9461997568E10|           12.048| 1.7525899264E11|1.23278000128E11|     1.239|       1.386|3.05453006848E11|      31.539|           41.1|        0.1486|    0.34390998|2.09498996736E11| 5.3640626176E10| 1.60506003456E11|         0.598|        0.167|     0.68586|      0.57377|      0.47094002|              USD|  MSFT|   en-US|    US|  Equity|Nasdaq Real Time ...|       true|                      HIGH|     NMS|   finmb_21835|    America/New_York|                      EDT|            -14400000|us_market|       false|              []|    1772845199|       1772830802|Microsoft Corpora...|Microsoft Corpora...|     CLOSED|          24.445877|           -28.793396|                 -0.06577538|                 -75.59515|                      -0.15600939|            15|                    0|            NULL|          NULL|    1.3 - Strong Buy|          false|                 -0.418818|            408.96|                true|              511108200000|            -0.41079634|         407.28|      -1.6799927|              -1.72|    408.5101 - 413.05|        NasdaqGS|                33590203|             64.16998|                  0.18611324|  344.79 - 555.45|            -146.49002|                  -0.26373214|                7.5757623| 1.7732736E9|       1.769634E9|            1777492800|          1777492800|               1.7696394E9|             1.7696394E9|                  true|                  15.99|  18.84224|       16.7292|  Microsoft|          1.3341|           NULL|    NULL|NULL|          NULL|

In [7]:
import great_expectations as gx
context = gx.get_context()

In [8]:
data_source_name = "test_dataset"
data_source = context.data_sources.add_spark(name=data_source_name)

In [11]:
validator = data_source.read_dataframe(df)
validator.expect_column_values_to_not_be_null("symbol")

AttributeError: 'SparkDatasource' object has no attribute 'read_dataframe'

In [4]:
spark.sql('''SHOW DATABASES;''').show()

+---------+
|namespace|
+---------+
|bronze_db|
|  default|
|  gold_db|
|silver_db|
+---------+

In [11]:
spark.sql('''SHOW TABLES;''').show()

+---------+---------+-----------+
|namespace|tableName|isTemporary|
+---------+---------+-----------+
+---------+---------+-----------+

In [12]:
spark.sql(''' DROP TABLE lakehouse_prod.bronze_db.bronze_country_iso_profiles;''').show()

++
||
++
++

26/03/23 16:12:51 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: Master removed our application: KILLED
26/03/23 16:12:51 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exiting due to error from cluster scheduler: Master removed our application: KILLED
	at org.apache.spark.errors.SparkCoreErrors$.clusterSchedulerError(SparkCoreErrors.scala:291)
	at org.apache.spark.scheduler.TaskSchedulerImpl.error(TaskSchedulerImpl.scala:981)
	at org.apache.spark.scheduler.cluster.StandaloneSchedulerBackend.dead(StandaloneSchedulerBackend.scala:165)
	at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint.markDead(StandaloneAppClient.scala:263)
	at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anonfun$receive$1.applyOrElse(StandaloneAppClient.scala:170)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:115)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

In [7]:
spark.stop()